import { Project, Task } from '@/types'

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: 'E-Commerce Platform Redesign',
    description: 'Complete redesign of the e-commerce platform with modern UI/UX',
    status: 'InProgress',
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    progress: 65,
    budget: 150000,
    createdAt: '2024-01-10',
    updatedAt: '2024-03-20',
    tasks: [
      {
        id: 't1',
        projectId: '1',
        title: 'Design new product page',
        description: 'Create mockups for product detail pages',
        status: 'Done',
        priority: 'High',
        assignedTo: 'dev@example.com',
        createdAt: '2024-01-15',
        updatedAt: '2024-02-10',
      },
      {
        id: 't2',
        projectId: '1',
        title: 'Implement shopping cart',
        description: 'Build shopping cart functionality with Redux',
        status: 'InProgress',
        priority: 'Critical',
        assignedTo: 'dev@example.com',
        createdAt: '2024-02-01',
        updatedAt: '2024-03-15',
      },
    ],
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Native mobile app for iOS and Android',
    status: 'Planning',
    startDate: '2024-04-01',
    endDate: '2024-12-31',
    progress: 15,
    budget: 250000,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-25',
    tasks: [
      {
        id: 't3',
        projectId: '2',
        title: 'Setup React Native project',
        description: 'Initialize RN project with TypeScript',
        status: 'InProgress',
        priority: 'High',
        assignedTo: 'pm@example.com',
        createdAt: '2024-04-01',
        updatedAt: '2024-04-05',
      },
    ],
  },
  {
    id: '3',
    name: 'API Microservices Migration',
    description: 'Migrate monolithic API to microservices architecture',
    status: 'OnHold',
    startDate: '2024-02-01',
    endDate: '2024-08-31',
    progress: 40,
    budget: 180000,
    createdAt: '2024-01-20',
    updatedAt: '2024-03-10',
    tasks: [],
  },
  {
    id: '4',
    name: 'Data Analytics Dashboard',
    description: 'Real-time analytics dashboard with charts and insights',
    status: 'InProgress',
    startDate: '2024-03-01',
    endDate: '2024-07-31',
    progress: 55,
    budget: 120000,
    createdAt: '2024-02-15',
    updatedAt: '2024-03-22',
    tasks: [
      {
        id: 't4',
        projectId: '4',
        title: 'Integrate Recharts library',
        description: 'Add Recharts for data visualization',
        status: 'Done',
        priority: 'Medium',
        assignedTo: 'dev@example.com',
        createdAt: '2024-03-01',
        updatedAt: '2024-03-10',
      },
      {
        id: 't5',
        projectId: '4',
        title: 'Build metrics API endpoints',
        description: 'Create endpoints for fetching analytics data',
        status: 'Review',
        priority: 'High',
        assignedTo: 'pm@example.com',
        createdAt: '2024-03-05',
        updatedAt: '2024-03-18',
      },
    ],
  },
  {
    id: '5',
    name: 'Customer Portal Enhancement',
    description: 'Add new features to customer self-service portal',
    status: 'Completed',
    startDate: '2023-11-01',
    endDate: '2024-02-28',
    progress: 100,
    budget: 90000,
    createdAt: '2023-10-15',
    updatedAt: '2024-02-28',
    tasks: [],
  },
  {
    id: '6',
    name: 'Security Audit & Compliance',
    description: 'Complete security audit and implement compliance measures',
    status: 'InProgress',
    startDate: '2024-01-10',
    endDate: '2024-05-31',
    progress: 70,
    budget: 110000,
    createdAt: '2024-01-05',
    updatedAt: '2024-03-20',
    tasks: [],
  },
  {
    id: '7',
    name: 'AI Chatbot Integration',
    description: 'Integrate AI-powered chatbot for customer support',
    status: 'Planning',
    startDate: '2024-05-01',
    endDate: '2024-09-30',
    progress: 5,
    budget: 200000,
    createdAt: '2024-04-01',
    updatedAt: '2024-04-10',
    tasks: [],
  },
  {
    id: '8',
    name: 'Performance Optimization',
    description: 'Optimize application performance and reduce load times',
    status: 'InProgress',
    startDate: '2024-02-15',
    endDate: '2024-06-15',
    progress: 50,
    budget: 75000,
    createdAt: '2024-02-01',
    updatedAt: '2024-03-21',
    tasks: [],
  },
  {
    id: '9',
    name: 'Payment Gateway Integration',
    description: 'Integrate multiple payment gateways',
    status: 'Completed',
    startDate: '2023-12-01',
    endDate: '2024-03-15',
    progress: 100,
    budget: 85000,
    createdAt: '2023-11-20',
    updatedAt: '2024-03-15',
    tasks: [],
  },
  {
    id: '10',
    name: 'Documentation Portal',
    description: 'Create comprehensive documentation portal for developers',
    status: 'OnHold',
    startDate: '2024-03-01',
    endDate: '2024-08-31',
    progress: 25,
    budget: 60000,
    createdAt: '2024-02-20',
    updatedAt: '2024-03-05',
    tasks: [],
  },
]

export function getMockProjects(): Promise<Project[]> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(MOCK_PROJECTS), 500)
  })
}

export function getMockProjectById(id: string): Promise<Project | null> {
  return new Promise((resolve) => {
    setTimeout(() => {
      const project = MOCK_PROJECTS.find((p) => p.id === id) || null
      resolve(project)
    }, 300)
  })
}
